# Generated by Django 4.0.1 on 2022-01-14 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeatedPremise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Кадастровый номер')),
                ('postcode', models.CharField(blank=True, max_length=6, null=True, verbose_name='Индекс')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='Район')),
                ('locality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Населенный пункт')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица')),
                ('house_number', models.PositiveSmallIntegerField(blank=True, max_length=6, null=True, verbose_name='Дом')),
                ('apartment_number', models.PositiveSmallIntegerField(blank=True, max_length=6, null=True, verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Адрес отапливаемого помещения',
                'verbose_name_plural': 'Адреса отапливаемых помещений',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_statement', models.PositiveSmallIntegerField(verbose_name='Номер заявления')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата заявления')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sobnushdi.heatedpremise', verbose_name='Адрес отапливаемого помещения')),
            ],
            options={
                'verbose_name': 'Заявление',
                'verbose_name_plural': 'Заявления',
            },
        ),
    ]
