# Generated by Django 4.0.1 on 2022-01-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_person_statement_and_more'),
        ('sobnushdi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_decree', models.CharField(max_length=7, verbose_name='номер распоряжения')),
                ('date_decree', models.DateField(blank=True, null=True, verbose_name='дата распоряжения')),
                ('number', models.CharField(blank=True, max_length=7, null=True, verbose_name='номер договора')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.AddField(
            model_name='statement',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Заявление'),
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='номер деляны')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата?')),
                ('forestry', models.CharField(blank=True, max_length=50, null=True, verbose_name='Лесничество')),
                ('district_forestry', models.CharField(blank=True, max_length=50, null=True, verbose_name='Участковое лесничество')),
                ('tract', models.CharField(blank=True, max_length=50, null=True, verbose_name='Урочище')),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Квартал')),
                ('section', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Выдел')),
                ('number_plot', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер делянки')),
                ('chop_type', models.CharField(max_length=2, verbose_name='Вид рубки')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sobnushdi.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Делянка',
                'verbose_name_plural': 'Делянки',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sobnushdi.statement', verbose_name='Заявление'),
        ),
    ]
