# Generated by Django 4.0.1 on 2022-03-22 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveSmallIntegerField(verbose_name='Серия')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('issued', models.CharField(blank=True, max_length=250, null=True, verbose_name='Кем выдан')),
                ('address_birth', models.TextField(blank=True, default='Колосовка', max_length=500, null=True, verbose_name='Место рождения')),
                ('inn', models.PositiveIntegerField(blank=True, null=True, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Паспортные данные',
                'verbose_name_plural': 'Паспортные данные',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ResidenceAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(blank=True, default='646350', max_length=6, null=True, verbose_name='Индекс')),
                ('region', models.CharField(blank=True, default='Омская', max_length=100, null=True, verbose_name='Область')),
                ('district', models.CharField(blank=True, default='Колосовский', max_length=50, null=True, verbose_name='Район')),
                ('locality', models.CharField(blank=True, default='Колосовка', max_length=50, null=True, verbose_name='Населенный пункт')),
                ('street', models.CharField(blank=True, default='Кирова', max_length=50, null=True, verbose_name='Улица')),
                ('house_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Дом')),
                ('apartment_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Адрес проживания',
                'verbose_name_plural': 'Адреса проживания',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('date_of_bird', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='Телефон')),
                ('passport', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.passport', verbose_name='паспортные данные')),
                ('residence_address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.residenceaddress', verbose_name='Адрес проживания')),
            ],
            options={
                'verbose_name': 'ФИО',
                'verbose_name_plural': 'ФИО',
                'ordering': ['id'],
            },
        ),
    ]
