# Generated by Django 4.0.1 on 2022-01-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='statement',
        ),
        migrations.AlterField(
            model_name='person',
            name='residence_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.residenceaddress', verbose_name='Адрес проживания'),
        ),
    ]
